USE [master]
GO

/****** Object:  Database [StudentProgress]    Script Date: 4/23/2025 8:52:07 PM ******/
CREATE DATABASE [StudentProgress]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StudentProgress', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StudentProgress.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StudentProgress_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StudentProgress_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudentProgress].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudentProgress] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudentProgress] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudentProgress] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudentProgress] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudentProgress] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudentProgress] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StudentProgress] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudentProgress] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudentProgress] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudentProgress] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudentProgress] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudentProgress] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudentProgress] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudentProgress] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudentProgress] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StudentProgress] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudentProgress] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudentProgress] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudentProgress] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudentProgress] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudentProgress] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StudentProgress] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudentProgress] SET RECOVERY FULL 
GO

ALTER DATABASE [StudentProgress] SET  MULTI_USER 
GO

ALTER DATABASE [StudentProgress] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudentProgress] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudentProgress] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudentProgress] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StudentProgress] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudentProgress] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StudentProgress] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StudentProgress] SET  READ_WRITE 
GO


